site_name: stardust-py
site_description: Stardust Python module
site_author: Nova King

repo_url: https://github.com/technobaboo/stardust-py
edit_uri: https://github.com/technobaboo/stardust-py/edit/main/docs

theme: readthedocs

markdown_extensions:
  - codehilite

nav:
  - Home: index.md
  - Advanced: advanced.md
  - About:
    - Release Notes: about/changelog.md
    - Contributing: about/contributing.md
    - License: about/license.md
